version: '3.7'

services:
  database:
    image: mysql:5.7
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root   
    ports:
      - 3306:3306
    volumes:
      - ./database_data:/var/lib/mysql
    networks:
      - database_net
  adminer:
    image: dehy/adminer
    networks:
      - database_net
    ports:
      - 8090:80

networks:
  database_net:
    driver: bridge