apiVersion: apps/v1
kind: Deployment
metadata:
  name: www-2
  namespace: production
spec:
  replicas: 3
  selector: 
    matchLabels:
       app: www
  template:
    metadata:
       labels:
         app: www
    spec:
       containers:
         - name: nginx
           image: nginx:1.16-alpine
           ports:
            - containerPort: 80