apiVersion: v1
kind: Pod
metadata:
  name: db
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd         
  containers:
    - name: mysql
      image:  mysql:5.7
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: mysqlpwd
      volumeMounts:
      - name: data
        mountPath: /var/lib/mysql
  volumes:
  - name: data
    emptyDir: {}
