FROM ubuntu:latest
RUN apt-get update && apt-get install -y \
python3 \
python3-pip
#RUN pip install flask
#RUN pip install mysql-connector-python
#WORKDIR ./
#COPY ./app.py /app.py
CMD python3 app.py
#RUN echo “I am run during image building”